src/main/java/com/team1/moim/domain/event/controller/EventController.java, src/main/java/com/team1/moim/domain/group/controller/GroupController.java
=> [Fix] URI 수정

src/main/java/com/team1/moim/global/config/security/SecurityConfig.java, src/main/java/com/team1/moim/global/config/security/WebConfig.java
* #41 
* SecurityConfig에 Cors 관련 코드 추가
=> [Fix/Auth] Axios 로그인 요청 시 CORS 에러 이슈 해결

src/main/java/com/team1/moim/domain/group/dto/response/GroupDetailResponse.java
=> [Fix] 모임 순환참조 해결

src/main/java/com/team1/moim/domain/event/repository/EventRepository.java
=> 삭제안된 일정만 조회

src/main/java/com/team1/moim/domain/event/controller/EventController.java, src/main/java/com/team1/moim/domain/event/service/EventService.java
- 이슈 없이 긴급 수정
- 업로드된 파일을 수정할 때 수정이 되지 않고, TOO MANY REQUEST 302 오류가 발생하는 것을 수정
=> [Feat] 업로드된 파일 수정

src/main/java/com/team1/moim/domain/event/service/EventService.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java, src/main/java/com/team1/moim/domain/notification/controller/NotificationController.java, src/main/java/com/team1/moim/domain/notification/dto/EventNotification.java, src/main/java/com/team1/moim/domain/notification/service/NotificationService.java, src/main/java/com/team1/moim/global/config/sse/controller/SseController.java
=> [Fix] 알림 메시지 틀 수정

src/main/java/com/team1/moim/domain/group/controller/GroupController.java, src/main/java/com/team1/moim/domain/group/dto/response/FindPendingGroupResponse.java
=> 확정되지 않은 그룹조회 response 수정

src/main/java/com/team1/moim/domain/group/dto/response/ListGroupResponse.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> 모임 response 수정

src/main/java/com/team1/moim/domain/group/controller/GroupController.java, src/main/java/com/team1/moim/domain/group/dto/response/FindConfirmedGroupResponse.java, src/main/java/com/team1/moim/domain/group/entity/Group.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> [Feat] 모임 확정 기능 - 알림전송

src/main/java/com/team1/moim/domain/event/dto/request/EventRequest.java, src/main/java/com/team1/moim/domain/group/controller/GroupController.java, src/main/java/com/team1/moim/domain/group/dto/response/FindConfirmedGroupResponse.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> [Feat] 모임 취소 - 호스트

src/main/java/com/team1/moim/domain/group/repository/GroupRepository.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> 취소된 모임 리스트에 추가

src/main/java/com/team1/moim/domain/group/repository/GroupRepository.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> 모임 투표마감시간 도달 시 확정/취소, 알림 전송

build.gradle, src/main/java/com/team1/moim/domain/chat/config/StompExceptionHandler.java, src/main/java/com/team1/moim/domain/chat/config/StompHandler.java, src/main/java/com/team1/moim/domain/chat/config/WebSocketConfig.java, src/main/java/com/team1/moim/domain/chat/controller/ChatController.java, src/main/java/com/team1/moim/domain/chat/dto/request/ChatRequest.java, src/main/java/com/team1/moim/domain/chat/dto/response/ChatResponse.java, src/main/java/com/team1/moim/domain/chat/entity/Chat.java, src/main/java/com/team1/moim/domain/chat/entity/MemberRoom.java, src/main/java/com/team1/moim/domain/chat/entity/MessageType.java, src/main/java/com/team1/moim/domain/chat/entity/Room.java, src/main/java/com/team1/moim/domain/chat/repository/ChatRepository.java, src/main/java/com/team1/moim/domain/chat/repository/RoomRepository.java, src/main/java/com/team1/moim/domain/chat/service/ChatService.java, src/main/java/com/team1/moim/domain/event/service/EventService.java, src/main/java/com/team1/moim/domain/group/dto/response/VoteResponse.java, src/main/java/com/team1/moim/domain/notification/dto/NotificationResponseNew.java, src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java, src/main/java/com/team1/moim/global/config/security/oauth2/userinfo/OAuth2UserInfo.java, src/main/java/com/team1/moim/global/exception/UnauthorizedException.java
> * #112 
> - 웹소켓 시큐리티 처리
> - 채팅 기능에 필요한 엔티티 설계
> - 채팅 로직과 관련된 dto, controller, service, repository 작성
=> [Feat] 채팅 기능 개발

src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> 모임 스케쥴러에 그룹타입 추가

src/main/java/com/team1/moim/domain/event/controller/EventController.java, src/main/java/com/team1/moim/domain/event/dto/response/TodoResponse.java, src/main/java/com/team1/moim/domain/event/entity/ToDoList.java, src/main/java/com/team1/moim/domain/event/exception/TodoNotFoundException.java, src/main/java/com/team1/moim/domain/event/repository/ToDoListRepository.java, src/main/java/com/team1/moim/domain/event/service/EventService.java, src/main/java/com/team1/moim/global/exception/ErrorCode.java
=> todolist 조회, 체크 변경 api 생성

src/main/java/com/team1/moim/domain/chat/controller/RoomController.java, src/main/java/com/team1/moim/domain/chat/dto/response/RoomListResponse.java, src/main/java/com/team1/moim/domain/chat/repository/MemberRoomRepository.java, src/main/java/com/team1/moim/domain/chat/repository/RoomRepository.java, src/main/java/com/team1/moim/domain/chat/service/RoomService.java
> ex) * #이슈번호
> 채팅 리스트 조회 api추가
=> 채팅 리스트 조회 api

src/main/java/com/team1/moim/domain/chat/dto/request/RoomRequest.java, src/main/java/com/team1/moim/domain/chat/dto/response/RoomDetailResponse.java, src/main/java/com/team1/moim/domain/chat/entity/Room.java, src/main/java/com/team1/moim/domain/group/controller/GroupController.java, src/main/java/com/team1/moim/domain/group/dto/response/GroupDetailResponse.java, src/main/java/com/team1/moim/domain/group/service/GroupService.java
=> 그룹 디테일 조회(타입 전체)

src/main/java/com/team1/moim/domain/group/service/GroupService.java
> ex) * #이슈번호
> 그룹아이디를 키값으로 추천일정이 레디스에 담겨있으면 또 레디스에 들어가지 않게 수정함
=> 모임 추천일정 레디스에 중복으로 안담기게 수정

src/main/java/com/team1/moim/domain/chat/dto/response/RoomListResponse.java
=> 채팅 리스트 response 수정

k8s/depl-serv.yml
=> docekr-secret 설정

k8s/depl-serv.yml
=> redis host 변경

.gitignore, k8s/depl-serv.yml, src/main/resources/application.yml
=> yml 시크릿 처리, gitignore 제거

src/main/java/com/team1/moim/domain/chat/controller/ChatController.java
> ex) * #이슈번호
- 사용자가 클릭한 채팅룸으로 웹소켓 연결을 맺을 수 있도록 처리함
>
=> [Feat] 사용자가 클릭한 채팅룸으로 웹소켓 연결을 맺을 수 있도록 처리

src/main/java/com/team1/moim/domain/chat/controller/ChatController.java, src/main/java/com/team1/moim/domain/chat/repository/ChatRepository.java, src/main/java/com/team1/moim/domain/chat/service/ChatService.java
> ex) * #이슈번호
- 각 채팅룸 별로 이전 채팅 기록을 가져올 수 있도록 설정
- JPA 기능을 활용해서 간단하게 조회
=> [Feat] 각 채팅방의 과거 채팅 기록 조회

src/main/java/com/team1/moim/domain/chat/service/RoomService.java
=> [Chore] 한 페이지 당 불러오는 채팅룸 7개로 수정

src/main/java/com/team1/moim/domain/chat/entity/Room.java, src/main/java/com/team1/moim/domain/chat/repository/RoomRepository.java, src/main/java/com/team1/moim/domain/chat/service/RoomService.java
=> 채팅 스케쥴러 종료(+알람), 종료 10분 전 알람 ,종료된 채팅 리스트에서제거

src/main/java/com/team1/moim/domain/notification/controller/NotificationController.java, src/main/java/com/team1/moim/domain/notification/dto/NotificationResponseNew.java, src/main/java/com/team1/moim/domain/notification/service/NotificationService.java, src/main/java/com/team1/moim/global/config/redis/RedisService.java
=> 알림 클릭 시 redis 삭제

src/main/java/com/team1/moim/domain/member/entity/Member.java
=> [Fix] 닉네임과 패스워드에 글자 수 제한 추가
